language: ruby

rvm:
  - 1.9.2
  - 1.9.3
  - 1.8.7

before_install:
  - gem update --system
  - gem -v

before_script:
  - cp config/{database.yml.example,database.yml}
  - bundle exec rake db:setup

bundler_args: --without development production
